// ----------------- Mode Switching -----------------
const menuHomework = document.getElementById("menuHomework");
const menuGuided = document.getElementById("menuGuided");
const menuProgress = document.getElementById("menuProgress");
const homeworkPanel = document.getElementById("homeworkPanel");
const guidedPanel = document.getElementById("guidedPanel");
const progressPanel = document.getElementById("progressPanel");

function setMode(mode) {
  const isHomework = mode === "homework";
  const isGuided = mode === "guided";
  const isProgress = mode === "progress";

  menuHomework.classList.toggle("active", isHomework);
  menuGuided.classList.toggle("active", isGuided);
  menuProgress.classList.toggle("active", isProgress);

  homeworkPanel.style.display = isHomework ? "block" : "none";
  guidedPanel.style.display = isGuided ? "block" : "none";
  progressPanel.style.display = isProgress ? "block" : "none";

  if (isGuided) guidedInit();
  if (isProgress) loadProgress();
}

menuHomework.addEventListener("click", () => setMode("homework"));
menuGuided.addEventListener("click", () => setMode("guided"));
menuProgress.addEventListener("click", () => setMode("progress"));

// ----------------- Homework Generator + Grader -----------------
const hwGrade = document.getElementById("hwGrade");
const hwTopic = document.getElementById("hwTopic");
const hwDifficulty = document.getElementById("hwDifficulty");
const hwCount = document.getElementById("hwCount");

const generateBtn = document.getElementById("generateBtn");
const gradeBtn = document.getElementById("gradeBtn");

const problemsContainer = document.getElementById("problemsContainer");
const scoreContainer = document.getElementById("scoreContainer");
const studentNameLabel = document.getElementById("studentNameLabel");
const sessionStudentNameEl = document.getElementById("sessionStudentName");
const sessionDateEl = document.getElementById("sessionDate");
const sessionDurationEl = document.getElementById("sessionDuration");
const progressSummaryEl = document.getElementById("progressSummary");
const weakTopicsListEl = document.getElementById("weakTopicsList");
const topicStatsEl = document.getElementById("topicStats");
const recentActivityEl = document.getElementById("recentActivity");

let homeworkState = null;
const studentId = getOrCreateStudentId();
if (studentNameLabel) studentNameLabel.innerText = studentId;
if (sessionStudentNameEl) sessionStudentNameEl.innerText = studentId;

function tutorEndpoint() {
  // Netlify dev serves static files on :3999 and functions/proxy on :8888.
  // If user opens :3999 directly (localhost or 127.0.0.1), force requests to :8888.
  if (location.port === "3999") {
    return `${location.protocol}//${location.hostname}:8888/.netlify/functions/tutor`;
  }
  return "/.netlify/functions/tutor";
}

function getOrCreateStudentId() {
  const key = "plc_student_id";
  let id = localStorage.getItem(key);
  // Migrate legacy autogenerated IDs to a readable default name.
  if (!id || /^student_[a-z0-9]+$/i.test(id) || id === "Jassi") {
    id = "Jassi Paul";
    localStorage.setItem(key, id);
  }
  return id;
}

function updateSessionDate() {
  if (!sessionDateEl) return;
  const now = new Date();
  sessionDateEl.innerText = now.toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatDuration(seconds) {
  const h = String(Math.floor(seconds / 3600)).padStart(2, "0");
  const m = String(Math.floor((seconds % 3600) / 60)).padStart(2, "0");
  const s = String(seconds % 60).padStart(2, "0");
  return `${h}:${m}:${s}`;
}

function startSessionTimer() {
  if (!sessionDurationEl) return;
  const startedAt = Date.now();
  const tick = () => {
    const elapsed = Math.max(0, Math.floor((Date.now() - startedAt) / 1000));
    sessionDurationEl.innerText = formatDuration(elapsed);
  };
  tick();
  setInterval(tick, 1000);
}

function renderProgress(progress) {
  if (!progress) return;
  const t = progress.totals || {};
  if (progressSummaryEl) {
    progressSummaryEl.innerHTML = `
      <div class="stat-card"><b>Attempts</b><div class="mono">${t.attempts ?? 0}</div></div>
      <div class="stat-card"><b>Correct</b><div class="mono">${t.correct ?? 0}</div></div>
      <div class="stat-card"><b>Incorrect</b><div class="mono">${t.incorrect ?? 0}</div></div>
      <div class="stat-card"><b>Accuracy</b><div class="mono">${t.accuracy ?? 0}%</div></div>
    `;
  }

  const weak = Array.isArray(progress.weakTopics) ? progress.weakTopics : [];
  if (weakTopicsListEl) {
    weakTopicsListEl.innerHTML = weak.length
      ? weak.map((w) => `${w.topic}: ${w.accuracy}% (${w.correct}/${w.attempts})`).join("<br/>")
      : "No weak topics yet (need at least 2 attempts per topic).";
  }

  const byTopic = progress.byTopic || {};
  const topics = Object.entries(byTopic);
  if (topicStatsEl) {
    topicStatsEl.innerHTML = topics.length
      ? topics.map(([topic, s]) => `${topic}: ${s.accuracy}% (${s.correct}/${s.attempts})`).join("<br/>")
      : "No topic attempts yet.";
  }

  const events = Array.isArray(progress.recentEvents) ? progress.recentEvents : [];
  if (recentActivityEl) {
    recentActivityEl.innerHTML = events.length
      ? events
          .slice(0, 8)
          .map((e) => `${new Date(e.ts).toLocaleString()} - ${e.mode}/${e.topic} - ${e.isCorrect ? "Correct" : "Incorrect"}`)
          .join("<br/>")
      : "No activity yet.";
  }
}

async function loadProgress() {
  const res = await fetch(tutorEndpoint(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      mode: "progress_summary",
      studentId,
    }),
  });
  const data = await res.json();
  if (data.ok) renderProgress(data.progress);
}

function renderProblems(problemList) {
  problemsContainer.innerHTML = "";
  scoreContainer.innerHTML = "";

  for (const p of problemList) {
    const div = document.createElement("div");
    div.className = "problem";
    div.innerHTML = `
      <div><b>Q${p.id}.</b> ${p.question}</div>
      <div style="margin-top:8px;">
        <input id="ans_${p.id}" placeholder="Answer (examples: 7/12 or 2 1/3)" />
      </div>
      <div id="res_${p.id}" class="result"></div>
    `;
    problemsContainer.appendChild(div);
  }
}

async function generateHomework() {
  const grade = hwGrade.value;
  const topic = hwTopic.value;
  const difficulty = hwDifficulty.value;
  const count = hwCount.value;

  const res = await fetch(tutorEndpoint(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      mode: "homework_generate",
      studentId,
      grade,
      topic,
      difficulty,
      count,
    }),
  });

  const data = await res.json();

  if (!data.ok) {
    scoreContainer.innerHTML = `<span class="bad">Error:</span> ${data.error || "Failed to generate"}`;
    return;
  }

  homeworkState = data.state;
  renderProblems(data.homework.problems);
}

async function gradeHomework() {
  if (!homeworkState) {
    scoreContainer.innerHTML = `<span class="bad">Generate homework first.</span>`;
    return;
  }

  const studentAnswers = {};
  for (const p of homeworkState.problems) {
    const inp = document.getElementById(`ans_${p.id}`);
    studentAnswers[p.id] = inp ? inp.value.trim() : "";
  }

  const res = await fetch(tutorEndpoint(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      mode: "homework_grade",
      studentId,
      state: homeworkState,
      studentAnswers,
    }),
  });

  const data = await res.json();

  if (!data.ok) {
    scoreContainer.innerHTML = `<span class="bad">Error:</span> ${data.error || "Failed to grade"}`;
    return;
  }

  for (const r of data.results) {
    const el = document.getElementById(`res_${r.id}`);
    if (!el) continue;

    if (r.isCorrect) {
      el.innerHTML = `<span class="good">✅ Correct</span>`;
    } else {
      el.innerHTML = `<span class="bad">❌ Incorrect</span> &nbsp; Correct: <b>${r.correctAnswer}</b><br/><span class="small">${r.feedback}</span>`;
    }
  }

  const s = data.summary;
  scoreContainer.innerHTML = `<b>Score:</b> ${s.correct}/${s.total} (${s.scorePercent}%)`;
  renderProgress(data.progress);
}

generateBtn.addEventListener("click", generateHomework);
gradeBtn.addEventListener("click", gradeHomework);

// ----------------- Guided Tutor -----------------
const chatBox = document.getElementById("chatBox");
const userInput = document.getElementById("userInput");
const sendBtn = document.getElementById("sendBtn");
const restartBtn = document.getElementById("restartBtn");

let guidedState = null;
let guidedInitialized = false;

function appendMessage(text, sender) {
  const div = document.createElement("div");
  div.className = `message ${sender}`;
  div.innerText = text;
  chatBox.appendChild(div);
  chatBox.scrollTop = chatBox.scrollHeight;
}

async function guidedWelcome() {
  const res = await fetch(tutorEndpoint(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ mode: "guided_welcome" }),
  });

  const data = await res.json();
  guidedState = data.state || null;
  appendMessage(data.tutor?.text || "Welcome to Guided Tutor.", "tutor");
}

function guidedInit() {
  if (guidedInitialized) return;
  guidedInitialized = true;
  chatBox.innerHTML = "";
  guidedWelcome();
}

async function sendGuided() {
  const msg = userInput.value.trim();
  if (!msg) return;
  userInput.value = "";

  appendMessage(msg, "user");

  const res = await fetch(tutorEndpoint(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      mode: "guided_answer",
      studentId,
      state: guidedState,
      studentAnswer: msg,
    }),
  });

  const data = await res.json();
  guidedState = data.state || guidedState;
  appendMessage(data.tutor?.text || "(No response)", "tutor");
  loadProgress();
}

sendBtn.addEventListener("click", sendGuided);
userInput.addEventListener("keydown", (e) => {
  if (e.key === "Enter") sendGuided();
});

restartBtn.addEventListener("click", () => {
  chatBox.innerHTML = "";
  guidedInitialized = false;
  guidedInit();
});

loadProgress();
setMode("homework");
updateSessionDate();
startSessionTimer();
